
# This allows us to use the variable `$app_backend`, which is
# determined from the `$uri` by means of this translation.  Note that
# evaluation is lazy; this mapping will only be done when the variable
# is actually used somewhere, so there's no wasted processing.
map $uri $app_backend {
        "/wiki" "wiki";
        "/spec-bugs" "spec-bugs";
        "/doxygen" "doxygen";
        "/joomla_readwrite" "joomla_readwrite";
        # "~*^/(?<app>wiki|spec-bugs|doxygen|joomla_readwrite)" "$app";
}

# map $cookie_sxs_b:$cookie_sxs_a $auth_from_cookie {
#         "~*aZ(?<var1>.*)3:Q(?<var2>.*)" "Basic $var1$var2"
# }

# This section looks for the sxs_user cookie.  If not present, it
# returns the login page.  If present, it translates the cookie into
# an Authorization header, and returns @app_backends.
location ~ ^/(?<app>wiki|spec-bugs|doxygen|joomla_readwrite) {
        error_page 401 =403 @login;
        error_page 419 = @app_backends;
        if ($cookie_sxs != "empty") {
                return 419;
        }
        return 401;
}

location @login {
        limit_req zone=one;
        try_files /login.html =401;
        # HttpOnly, secure
}

# This location can only be reached from one of the other nginx
# locations, but it has to check that the Authorization header is
# valid, because we could have the right cookies, but the wrong values
# stored in those cookies.
location @app_backends {
        error_page 401 =403 @login;
        proxy_set_header Authorization "Basic ${cookie_sxs}";
        auth_basic "SXS users";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass_header Authorization;

        # Note: An explicit resolver is necessary when using proxy_pass
        # with a variable, as we do in this section.  127.0.0.11 is
        # docker's built-in DNS resolver as of docker 1.10, and apparently
        # will not change any time soon.  If this does become a problem,
        # however, there's an interesting solution suggested at
        # http://stackoverflow.com/a/37656784/1194883
        resolver 127.0.0.11;

        # Forward the request to another container in this docker network.
        proxy_pass http://$app_backend;

        # In case there are any Location or Refresh headers are sent back
        # like http://wiki/, we want them rewritten appropriately.  The
        # default does not work when there is a variable in `proxy_pass`.
        proxy_redirect http://$app_backend https://$host/$app_backed;
}
