version: '3.7'

services:
  caddy:
    image: caddy:latest
    container_name: caddy_data_black_holes
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /web/servers/Caddyfile:/etc/caddy/Caddyfile:ro
      - /web/servers/data/document_root:/usr/share/caddy:ro
      - /web/servers/caddy_data:/data
      - /web/servers/caddy_config:/config
    user: "503:33"  # Map the container process to the host file owner

volumes:
  caddy_data:
  caddy_config:
