;;  -*- mode: Conf; comment-start: ";" -*-

; OPcache stores byte-compiled versions of the most frequently accessed PHP scripts
zend_extension=opcache.so

; This ensures that the `X-Powered-By: PHP/` header is not sent, though it should be removed by
; nginx anyway.
expose_php=Off

; Prevent arbitrary code to be loaded during runtime
enable_dl=Off

; disallow the use of assert()
assert.active=Off

; PHP will regenerate unknown session IDs. This effectively counteracts session fixation attacks.
session.use_strict_mode=On
session.cookie_httponly=On
session.cookie_lifetime=2678400 ; seconds
session.cookie_secure=On
session.save_path="/var/www/sessions"

; Hiding PHP errors helps hide possible ways hackers could manipulate the server
display_errors=Off
log_errors=On

; Nothing in the public joomla should accept file uploads
file_uploads=Off
upload_max_filesize=0

; We must allow url_fopen for one-click-update to work, but that should only be relevant to the
; read-write joomla container.  Instead, we disable all execution of remote data.
allow_url_fopen=Off
allow_url_include=Off

; Ignore arguments to mysql_connect()
sql.safe_mode=On
mysqli.default_host = "joomladb"
mysqli.default_port = "3306"
mysqli.default_user = "joomla_readonly"
mysqli.default_pw = "$mdp"

; Limit the time (measured in seconds) and resources any script can use
max_execution_time=2
max_input_time=2
memory_limit=64M

; Disable various dangerous functions.  The twitter plugin needs curl_exec.
disable_functions=exec,passthru,shell_exec,system,proc_open,popen,curl_multi_exec,parse_ini_file,show_source,phpinfo

; Limit PHP to only open scripts within this subdirectory
open_basedir=/var/www/html/

; Enable cgi.force_redirect for security reasons in a typical *Apache+PHP-CGI/FastCGI* setup
cgi.force_redirect=On
