version: '3.1'

services:
  cron:
    build: build
    restart: on-failure
    volumes:
      - /home/git/.ssh:/home/git/.ssh:ro
      - /home/git/.gitconfig:/home/git/.gitconfig:ro
      - /home/web/.ssh:/home/web/.ssh:ro
      - /home/web/.gitconfig:/home/web/.gitconfig:ro
      - /web/repos:/web/repos
      - /web/servers:/web/servers
      - /web/servers/cron/cron.d:/etc/cron.d
      - /web/servers/letsencrypt/certs:/etc/letsencrypt
      - /web/servers/letsencrypt/www:/var/www/letsencrypt
      - /sxs-annex:/sxs-annex
      - /sxs-annex8:/sxs-annex8
      - /nfs-data/Annex/SurrogateModeling.git:/nfs-data/Annex/SurrogateModeling.git
    logging:
      options:
        max-size: "100m"
