version: '3.1'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - joomla
      - wiki
      - oauth2
      - uwsgi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/document_root:/usr/share/nginx/html
      - ./nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - ../letsencrypt/certs:/etc/ssl/private:ro
      - ../letsencrypt/www:/var/www/letsencrypt:ro
      - ./wiki/document_root:/var/www/html/wiki:ro
      - ./wiki/document_root/conf/users.auth.php:/etc/nginx/.htpasswd:ro
      - ../data/document_root:/usr/share/nginx/html/data:ro
      - /sxs-annex/SimulationAnnex.git:/usr/share/nginx/html/waveforms_data/SimulationAnnex.git:ro
      - /nfs-data/Annex/SurrogateModeling.git:/usr/share/nginx/html/surrogate_data:ro
    logging:
      options:
        max-size: "100m"
    #command: [nginx-debug, '-g', 'daemon off;']  # add `error_log /var/log/nginx/error.log debug;` to see details

  oauth2:
    build: oauth2/build
    restart: on-failure
    volumes:
      - ./oauth2/www:/var/www/:ro
    logging:
      options:
        max-size: "100m"
    secrets:
      - source: oauth2_proxy_client_id
        target: client_id
      - source: oauth2_proxy_client_secret
        target: client_secret
      - source: oauth2_proxy_cookie_secret
        target: cookie_secret
      - source: github_app_private_key.pem
        target: github_app_private_key.pem
      - source: github_app_id
        target: github_app_id

  joomladb:
    image: mysql:5
    restart: on-failure
    volumes:
      - ./joomladb:/var/lib/mysql
    logging:
      options:
        max-size: "10m"

  joomla:
    image: joomla:3.8.2
    restart: on-failure
    command: bash -c "echo 'ServerName www.black-holes.org' >> /etc/apache2/apache2.conf && mdp=$$(cat /run/secrets/mdp) apache2-foreground"
    depends_on:
      - joomladb
    volumes:
      - ./joomla/php.ini:/usr/local/etc/php/conf.d/custom_php.ini:ro
      - ./joomla/document_root:/var/www/html:ro
      - ./joomla/document_root/cache:/var/www/html/cache  # Needs to be writeable
      - /var/www/sessions
    logging:
      options:
        max-size: "10m"
    secrets:
      - source: joomla_mysqli_default_pw
        target: mdp

  # ### NOTE: Running this at the same time as `joomla` (above) seems to be very dangerous.  This is the read-write
  # ### version of joomla, and should not be left running unless changes need to be made to the website.  Also, you
  # ### probably want to allow access to `/administrator` and remove `client_max_body_size` in nginx.conf, as well as
  # ### adjusting the `file_uploads` and `upload_max_filesize` variables in ./joomla/php.ini
  # joomla:
  #   image: joomla
  #   restart: "no"
  #   command: bash -c "echo 'ServerName www.black-holes.org' >> /etc/apache2/apache2.conf && mdp=$$(cat /run/secrets/mdp) apache2-foreground"
  #   depends_on:
  #     - joomladb
  #   volumes:
  #     - ./joomla/php.ini:/usr/local/etc/php/conf.d/custom_php.ini:ro
  #     - ./joomla/document_root:/var/www/html
  #     - /var/www/sessions
  #   logging:
  #     options:
  #       max-size: "10m"
  #   secrets:
  #     - source: joomla_readwrite_mysqli_default_pw
  #       target: mdp

  wiki:
    image: php:7-fpm
    restart: on-failure
    volumes:
      - ./wiki/document_root:/var/www/html/wiki
    logging:
      options:
        max-size: "10m"

  uwsgi:  # Used for serving download requests for data files
    build: ../data/uwsgi/build
    restart: on-failure
    environment:
      - GOOGLE_RECAPTCHA_SECRET=6Le3Ah4UAAAAADStZwhsviymeinCXfMbcuJnPCtV
    volumes:
      - ../data/document_root:/var/www/html
      - ../data/uwsgi/wsgi.ini:/var/www/wsgi.ini
      - ../data/uwsgi/download.py:/var/www/download.py
      - /sxs-annex/SimulationAnnex.git:/var/www/html/waveforms/SimulationAnnex.git:ro
      - /nfs-data/Annex/SurrogateModeling.git:/var/www/html/surrogates/storage:ro
    logging:
      options:
        max-size: "10m"



secrets:
  joomla_mysqli_default_pw:
    file: ../secrets/joomla_mysqli_default_pw
  joomla_readwrite_mysqli_default_pw:
    file: ../secrets/joomla_readwrite_mysqli_default_pw
  oauth2_proxy_client_id:
    file: ../secrets/oauth2_proxy_client_id
  oauth2_proxy_client_secret:
    file: ../secrets/oauth2_proxy_client_secret
  oauth2_proxy_cookie_secret:
    file: ../secrets/oauth2_proxy_cookie_secret
  github_app_private_key.pem:
    file: ../secrets/github_app_private_key.pem
  github_app_id:
    file: ../secrets/github_app_id
