events {
    # nginx fails if this block is not present, even though it's empty...
}

http {
    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        server_name  localhost;
        location / {
            set $response "Your request URI was '${request_uri}'.\n";
            set $response "${response}User login: ${http_x_user}\n";
            set $response "${response}User email: ${http_x_email}\n";
            set $response "${response}User memberships: ${http_x_memberships}\n";
            set $response "${response}The memberships are the user's github organizations and organization:team pairs.";
            return 200 $response;
        }
    }
}
