# The return code 444 is a custom nginx code that immediately drops the connection.  A real user
# would see the "This site can’t be reached" page.

location = /waveforms/catalog.test.php {
        return 444;
}
location = /data/waveforms/catalog.test.php {
        return 444;
}
location = /waveforms/catalog.php {
  if ($args) { return 444; }
  return 301 https://data.black-holes.org/waveforms/catalog.html;
}
location = /data/waveforms/catalog.php {
        return 444;
}
location = /wp-login.php {
        return 444;
}
location = /index.php {
        return 444;
}
