# Don't show the PHP version, etc., in pages returned from a proxy
proxy_hide_header X-Powered-By;

# These are headers that can help the proxied servers make relevant decisions
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

# The P3P header was a nice idea, but is not really used any more.  (See, e.g., the headers
# delivered by google <https://www.google.com/support/accounts/answer/151657> and facebook
# <http://fb.me/p3p>, or the wikipedia page <https://en.wikipedia.org/wiki/P3P>.)  Joomla has a
# pretty intense default P3P, so let's just remove P3P from everything.
proxy_hide_header P3P;

# Try to remove joomla's header saying to ignore caching.
add_header X-Cache-Status $upstream_cache_status;
proxy_ignore_headers Cache-Control;
proxy_hide_header Cache-Control;
proxy_hide_header Pragma;
add_header Cache-Control "public";

# Set some headers that will help avoid cross-site scripting.
# It would be nice to make the Content-Security-Policy header more strict, though that will be hard with our existing site.
add_header Content-Security-Policy "frame-ancestors 'self'; default-src https: 'unsafe-eval' 'unsafe-inline' https://www.google-analytics.com; font-src 'self' https://cdn.mathjax.org https://fonts.gstatic.com https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://www.google-analytics.com;connect-src https: wss:";
add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

# Full URL is sent making same-origin requests; only the origin of the request
# client is sent when making cross-origin requests.
add_header Referrer-Policy origin-when-cross-origin;

# See <https://hstspreload.org/?domain=black-holes.org>.  Their advice is to get
# everything working, then ramp up the max-age (5 minutes, then 1 week, then 1
# month, finally 2 years), fixing any problems at each stage.  Finally, once
# everything is set up and the max-age is 2 years, add `; preload` at the end of
# this header (after `includeSubDomains`).  The preload should get this site
# included in future browsers as a site on which the browser should go straight to
# https.  Note that 6 months is the minimum for inclusion on the preload list.
#
# This ensures that any browser that ever sees this header will go straight to
# HTTPS, rather than try HTTP again.  Note that `add_header` directives are
# inherited from the previous level if and only if there are no `add_header`
# directives defined on the current level.  So if any others are redefined, this
# should be added again.
#
# add_header Strict-Transport-Security "max-age=300; includeSubDomains" always;
# add_header Strict-Transport-Security "max-age=604800; includeSubDomains" always;
# add_header Strict-Transport-Security "max-age=2678400; includeSubDomains" always;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
