# Use variables so that nginx will survive if jupyter isn't running
resolver 127.0.0.11 valid=600s;
set $upstream_jupyter jupyter;

allow 203.86.207.203;  # NZ
allow 24.13.209.162;  # PR
allow 128.84.127.0/24;  # Snyder Hill
allow 74.79.158.15;  # 604 Space Sciences
deny all;

proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;

client_max_body_size 4096m;

# proxy_pass http://jupyter:9123;
proxy_pass http://$upstream_jupyter:8888;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# add_header Content-Security-Policy "default-src https: 'unsafe-inline'; connect-src https: wss:";

# auth_basic "SXS users";
# auth_basic_user_file /etc/nginx/.htpasswd;

# # If a request to these apps is unauthorized (after the browser
# # has offered the login dropdown), the user should be sent our
# # special login location.
# error_page 401 @login;
