location /auth/ {
        # Since this is the only exposed location on this server, we should limit the attack surface
        # as much as possible.  The auth_request calls made by nginx are always GET, even if the
        # original request was a POST, and the oauth2 spec says that a callback must be a GET.  So
        # we are free to restrict all requests to GET.
        limit_except GET {
                deny all;
        }

        # Handle errors with an informative page
        location /auth/login {
                include uwsgi_params;
                set $failure $upstream_http_x_auth_failure;
                uwsgi_param HTTP_X_Auth_Failure $failure;
                uwsgi_pass uwsgi://oauth2:8080;
        }

        location /auth/ {
                # We'll be adding headers to the response, so we have to include all the headers that were
                # already set elsewhere.
                include conf.d/headers.conf;

                # This is so that, e.g., javascript on data.black-holes.org can send requests here along
                # with credentials, and the browser will allow the response to actually be used.
                if ($http_origin ~ "\.black-holes\.org$") {
                        add_header Access-Control-Allow-Origin $http_origin;
                        add_header Access-Control-Allow-Credentials true;
                        add_header Access-Control-Allow-Methods GET;
                }

                # These set the headers of the request that will be sent to the oauth2 server.
                include uwsgi_params;
                uwsgi_param HTTP_HOST                    $host;
                uwsgi_param HTTP_X_Real_IP               $remote_addr;
                uwsgi_param HTTP_X_Scheme                $scheme;
                uwsgi_param HTTP_X_Auth_Request_Redirect $request_uri;

                # Handle errors with an informative page
                error_page 403 = /auth/login;
                uwsgi_intercept_errors on;

                # Pass the request along to the oauth2 server
                uwsgi_pass uwsgi://oauth2:8080;
        }

        # The response will contain a cookie that may contain private information.  Ensure that the
        # cookie ends with 'secure', so that the browser will only send it over https in the future.
        # Currently, the session cookie only contains information that is useful with our secret
        # key, but just in case...
        proxy_cookie_path / "/; secure;";
}
