location /oauth2/ {
        include conf.d/headers.conf;
        if ($http_origin ~ "\.black-holes\.org$") {
                add_header Access-Control-Allow-Origin $http_origin;
                add_header Access-Control-Allow-Credentials true;
                add_header Access-Control-Allow-Methods GET;
        }
        include uwsgi_params;
        uwsgi_param HTTP_HOST                    $host;
        uwsgi_param HTTP_X_Real_IP               $remote_addr;
        uwsgi_param HTTP_X_Scheme                $scheme;
        uwsgi_param HTTP_X_Auth_Request_Redirect $request_uri;
        uwsgi_pass uwsgi://oauth2:8080;
        proxy_cookie_path / "/; secure;";
}
